print('Enter list: ')
value_list=list(map(int,input().split(',')))
print(f"Your list: {value_list}")
max_value=max(value_list)
min_value=min(value_list)
value_list.remove(max_value)
value_list.remove(min_value)
summa=sum(value_list)
print(f'Maximum value={max_value}')
print(f'Minimum value={min_value}')
print(f'Sum of elements={summa}')